# Generated by Django 6.0.3 on 2026-03-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
