# Generated by Django 6.0.3 on 2026-03-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_is_verified_customuser_token_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"permissions": [("can_block_user", "Can block user")]},
        ),
    ]
