# Generated by Django 6.0.3 on 2026-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("headline", models.CharField(max_length=100, verbose_name="Тема письма")),
                ("body", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письмо",
                "ordering": ["headline"],
            },
        ),
        migrations.CreateModel(
            name="SendAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now=True, verbose_name="Дата и время рассылки")),
                (
                    "status",
                    models.CharField(
                        choices=[("successfully", "Успешно"), ("not_successfully", "Не успешно")],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("response", models.TextField(verbose_name="Ответ почтового сервера")),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sending",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="Дата и время начала рассылки")),
                ("end_time", models.DateTimeField(verbose_name="Дата и время окончания рассылки")),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("started", "Запущена"), ("done", "Завершена")],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Электронная почта")),
                ("full_name", models.CharField(max_length=100, verbose_name="Ф.И.О.")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["owner"],
            },
        ),
    ]
