# Generated by Django 6.0.3 on 2026-03-05 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="messages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="sending",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sending", to="mailing.message"
            ),
        ),
        migrations.AddField(
            model_name="sending",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sending", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="sendattempt",
            name="sending",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sending_attempts", to="mailing.sending"
            ),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="subscribers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="sending",
            name="subscribers",
            field=models.ManyToManyField(related_name="sending", to="mailing.subscriber"),
        ),
    ]
