# Generated by Django 6.0.3 on 2026-03-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["headline"], "verbose_name": "Письмо", "verbose_name_plural": "Письма"},
        ),
    ]
